// THIS IS AN AUTOGENERATED FILE.
// DO NOT EDIT THIS FILE DIRECTLY
window.defaultWallpapers = ["w1.jpg","w10.png","w11.jpg","w12.jpg","w13.jpg","w14.jpg","w15.png","w16.png","w17.png","w18.jpg","w19.jpg","w2.jpg","w20.jpg","w21.png","w22.jpg","w23.jpg","w3.jpg","w4.jpg","w5.jpg","w6.jpg","w7.png","w8.jpg","w9.png"]